### ISSUE TITLE
Utf8 header not center

### ISSUE THREAD

**Issue by Nguyen-Hoang-Nam** [goolord/alpha-nvim#1]
Your function longest_line failed in uft8, I suggest create a function to count utf8 length similar to [this](https://github.com/Nguyen-Hoang-Nam/yanil/blob/customize-ui/lua/yanil/utf8.lua)

![utf8](https://user-images.githubusercontent.com/74345759/132273136-ea70a0a7-a0ee-4f51-8734-90ac42a011fd.jpg)

**Comment by goolord** [comment]
i just pushed a commit that should fix this

https://github.com/goolord/alpha-nvim/commit/97ef0679ebd4a2cba171f1f32a4612bbc355c0c0#diff-ec96159a0e4ab00d2629897381414ffd88f8e88aa0b82e2f8ba6e24da2873239R15-R25

i decided to use `vim.fn.strdisplaywidth` because

1. should be accurate
2. don't have to write it myself
3. i don't really know the performance characteristics, but it shouldn't be too big an overhead since `longest_line` gets memoized

testing it on my machine seemed to fix the problem !
