### ISSUE TITLE
Some custom buttons respond slow 

### ISSUE THREAD

**Issue by experiacc** [goolord/alpha-nvim#10]
Adding custom buttons to dashboard theme is slow for some keys.
So far, I've tried this with keys c and d. Both wait for like 1 second to execute command.

For Example :-

dashboard.button( "c", "open config" , ":e ~/.config/nvim/init.lua<CR>"),

But if I replace c with something like s, it executes instantly.

**Comment by experiacc** [comment]
Ok turns out you were right it was this command specifically
```
n  cS            <Plug>CSurround
n  cs            <Plug>Csurround
```
from the plugin [vim-surround](https://github.com/tpope/vim-surround)
Anyway I can ignore those keybinds in alpha just like in startify ?

**Comment by goolord** [comment]
ok, i added the 'nowait' option to the buttons for each theme which should fix this. since it's desirable in some cases to turn this behavior off each theme's button function also has an additional optional keybind {opts} parameter. https://github.com/goolord/alpha-nvim/commit/119832cdf516aa3aea97ebf9bf8d1b0e2c642f23
