### ISSUE TITLE
Looks bad when whitespace is highlighted at the end of the line

### ISSUE THREAD

**Issue by tareqsiraj** [goolord/alpha-nvim#111]
I have whitespace highlighted at the end of the line by default, but it looks bad when the dashboard shows up.

```
" Vim script I use to enable the highlighting
highlight WhitespaceEOL ctermbg=DarkYellow guibg=DarkYellow
match WhitespaceEOL /\s\+$/
au BufWinEnter * match WhitespaceEOL /\s\+$/
au InsertEnter * match WhitespaceEOL /\s\+\%#\@<!$/
au InsertLeave * match WhitespaceEOL /\s\+$/
au BufWinLeave * call clearmatches()
let b:show_whitespace = 1
```

![Screenshot from 2022-05-19 23-25-54](https://user-images.githubusercontent.com/1815868/169445714-9c987297-ce9b-458e-abfd-120e7966dd41.png)

**Comment by drselump14** [comment]
Any fix for this issue?

**Comment by YodaEmbedding** [comment]
Solutions:

1. Eliminate the trailing whitespace.
2. Some autocmd that runs on alpha-nvim enter / exit. Then, just set the highlight group to guibg=NONE.

**Comment by goolord** [comment]
fixed in https://github.com/goolord/alpha-nvim/commit/f945f1294f97d2acf6bee085d47bfbbb5a8e3e72

i had mostly ignored this since you could easily solve this problem by setting `let b:show_whitespace = 1` or whatever in your alpha setup but i don't think anyone is going to ever want the right-margin to actually be filled in anyways
