### ISSUE TITLE
Undocumented options?

### ISSUE THREAD

**Issue by adrian5** [goolord/alpha-nvim#148]
Looking at the dashboard and startify theme templates, I noticed that some of the options used aren't documented anywhere. E.g. `shrink_margin` or the quite essential [`keymap`](https://github.com/goolord/alpha-nvim/blob/main/lua/alpha.lua#L360). Would be nice to have those added to the [docs](https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L76-L91).

**Comment by gennaro-tedesco** [comment]
I second this: I have been trying to set-up the startify screen without success (I find strange that the examples in the docs show how to set-up an _empty_ startify screen instead of a normal one).

**Comment by goolord** [comment]
this `require'alpha'.setup(require'alpha.themes.startify'.config)` *is* a "normal" startify screen. it reads from `oldfiles`, so if that's empty, so is the 'MRU' sections, if that's what you mean

**Comment by goolord** [comment]
documented more options here https://github.com/goolord/alpha-nvim/commit/54c9ba499209ac2563ddcefd47ba7bce35ae94ae

**Comment by gennaro-tedesco** [comment]
There is probably a tiny mistake [here](https://github.com/goolord/alpha-nvim/blob/da15a10f8875fed409241816bacd9378c5696449/doc/alpha.txt#L306), in the docs. It seems that in order to change the footer one must
```lua
startify.section.footer.val = {{ type = "text", val = "footer" },}
```
instead of just `startify.section.footer`, does it not (otherwise I cannot get it to show the footer, or am I wrong)?

**Comment by goolord** [comment]
ah yeah that's right, that was a typo. fixed @gennaro-tedesco
