### ISSUE TITLE
[FR] Allow to hide statusline and tabline

### ISSUE THREAD

**Issue by xfzv** [goolord/alpha-nvim#200]
It would be nice if we could disable statusline and tabline like with [goolord/alpha-nvim](https://github.com/goolord/alpha-nvim) to achieve a cleaner look:

Refs: [1](https://github.com/glepnir/dashboard-nvim/blob/4c2b038c5cfa70f90506f1551e5fd2d040174e08/lua/dashboard/init.lua#L48-L51) : [2](https://github.com/glepnir/dashboard-nvim/blob/4c2b038c5cfa70f90506f1551e5fd2d040174e08/lua/dashboard/init.lua#L104-L115)

**Comment by goolord** [comment]
you can do that already, i don't know if it belongs as an option in the code since you can easily write
`autocmd User AlphaReady set showtabline=0 | autocmd BufUnload <buffer> set showtabline=2`
or the lua equivalent https://github.com/goolord/alpha-nvim/blob/dafa11a6218c2296df044e00f88d9187222ba6b0/doc/alpha.txt#L339
