### ISSUE TITLE
show cmd output in floating window

### ISSUE THREAD

**Issue by danielnehrig** [goolord/alpha-nvim#50]
dashboard.nvim has the ability to cat files and put the output as a floating term on the dashboard screen
would be cool if we could have it here as well
it also allows for piping into lolcat etc
see: https://github.com/danielnehrig/nvim/blob/71d05338354edf3b8f1b8cc30fdec77ad74b5e60/lua/plugins/dashboard/init.lua

**Comment by goolord** [comment]
yeah this is easily doable i think, mostly adding another entry to `layout_element` and `keymaps_element` and making sure the geometry is correct, should be a pretty small change

**Comment by ben-hansske** [comment]
I would like to give this a try.

**Comment by danielnehrig** [comment]
@ben-hansske looking forward

**Comment by olimorris** [comment]
Hey all. Has anyone actively worked on a pull request for this? Recent changes in [dashboard.nvim](https://github.com/glepnir/dashboard-nvim/blob/master/lua/dashboard/preview.lua#L43) make it look quite simple

**Comment by goolord** [comment]
there exists a pr at https://github.com/goolord/alpha-nvim/pull/63, it's less simple for alpha since we're trying to get the window to change positions when there is a redraw. you can use this branch, the alpha api is extensible, if you are really so inclined it would probably be simple to add dashboard's terminal preview : )

**Comment by goolord** [comment]
`"terminal"` type added here https://github.com/goolord/alpha-nvim/pull/124
