### ISSUE TITLE
Wrong skip condition

### ISSUE THREAD

**Issue by meijieru** [goolord/alpha-nvim#54]
This [commit](https://github.com/goolord/alpha-nvim/commit/8a80e49b6c9824a56313f494f8cf35942bdfb885) should consider the `-u ${config_file}` case.
Currently it skips in that case though it should not.

**Comment by goolord** [comment]
why should it? if alpha is installed by packer, it's still in your rtp and is still going to run just like every other plugin you have installed

**Comment by meijieru** [comment]
Sorry, the link is broken. I just update the commit link.
Alpha is correctly loaded. It is the condition to activate that needs more considerations.

**Comment by goolord** [comment]
https://github.com/wbthomason/packer.nvim/issues/307
plugins installed by packer are installed to `stdpath('data')/nvim/site/pack/packer/start/` which is *always* sourced by neovim no matter what config it's reading, unless the `--clean` flag is passed. I don't think it's unreasonable that someone might want multiple configs that still have the alpha buffer automatically open, since I use nvim that way myself.

the solution to this is to mark alpha `opt = true` in `packer_use` i think, or to pass `--clean` to neovim.

if your config doesn't call `alpha.setup` the `VimEnter` autocmd shouldn't even be created in the first place

**Comment by meijieru** [comment]
The plugin is correctly loaded but doesn't show at startup.
This behavior comes after that commit.
I think the previous behavior is desired, is that correct?

**Comment by goolord** [comment]
oh, i see what you mean now. yeah i can fix that

**Comment by goolord** [comment]
pushed https://github.com/goolord/alpha-nvim/commit/b9eae5d1f767da26b03a6c822b80263b27fc0352, it should be more like the old conditions now except slightly more rigorous

**Comment by goolord** [comment]
lmk if the problem persists for you :black_heart:

**Comment by meijieru** [comment]
Problem solved. Thx!
